version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - aws --version
  build:
    commands:
      - echo Deployment started on `date`
      - ls

  post_build:
    commands:
      - echo Deployment completed on `date`

